jog_arm_server:
  simu: false
  cmd_in_topic: jog_arm_server/delta_jog_cmds
  cmd_frame:  base_link  # TF frame that incoming cmds are given in
  incoming_cmd_timeout:  1  # Stop jogging if X seconds elapse without a new cmd
  joint_topic: joint_states
  move_group_name: manipulator
  singularity_threshold:  7
  hard_stop_singularity_threshold: 12.0 # Stop when the condition number hits this
  cmd_out_topic: ur_driver/joint_speed
  planning_frame: base_link
  low_pass_filter_coeff: 2.5  # Larger c --> trust the filtered data more, trust the measurements less.
  pub_period: 0.0034  # 1/Nominal publish rate [seconds]
  scale:
    linear: 0.000005
    rotational: 0.000005
